package de.salt.sce.mapper.util;

import org.slf4j.Logger;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import static org.slf4j.LoggerFactory.getLogger;

public class ObjectSerializer {

    private final static Logger log = getLogger(ObjectSerializer.class);
    public static byte[] serialize(Object obj) {
        try {
            try (ByteArrayOutputStream b = new ByteArrayOutputStream()) {
                try (ObjectOutputStream o = new ObjectOutputStream(b)) {
                    o.writeObject(obj);
                }
                return b.toByteArray();
            }
        } catch (IOException e) {
            log.error("Error in serialization of files. The error is generated by the ObjectSerializer class function serialize. For detailed information, please check the info log.");
            log.info(e.getMessage());
        }
        return new byte[0];
    }

    public static Object deserialize(byte[] bytes) {
        try {
            try (ByteArrayInputStream b = new ByteArrayInputStream(bytes)) {
                try (ObjectInputStream o = new ObjectInputStream(b)) {
                    return o.readObject();
                }
            }
        } catch (IOException | ClassNotFoundException e) {
            log.error("Error in deserialization of files. The error is generated by the deserialize function of the ObjectSerializer class. For detailed information, please refer to the info log.");
            log.info(e.getMessage());
        }

        return new Object();
    }
}
